In [1]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)

In [6]:
import numpy as np
a = np.array
a = np.array([0, 1, 2])
print(type(a))

print(a.shape)
print(a[0])
print(a[1])
print(a[2])

a[0] = 5
print(a)

b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]
(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3

In [5]:
a = np.zeros((3,3))
print(a)

b = np.ones((2,2))
print(b)

c = np.full((3,3), 7)
print(c)

d = np.random.random((3,3))
print(d)

e = np.eye(3)
print(e)

f = np.array([2, 3, 1, 0])
print(f)

g = np.arange(20)
print(g)

h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

i = np.arange(1, 8, dtype=float)
print(i)

j = np.linspace(2, 4, 5)
print(j)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.30598995 0.7815768  0.64374537]
 [0.61640498 0.07789895 0.1300418 ]
 [0.0916659  0.2327783  0.29517495]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]

In [8]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])

z = np.array([5, 6], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64

In [9]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])

temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)

cond = arr > 0
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]

In [10]:
import numpy as np
a = np.array([1, 2, 5, 3])

print ("Adding 1 to every element:", a+1)
print ("Subtracting 3 from each element:", a-3)
print ("Multiplying each element by 10:", a*10)
print ("Squaring each element:", a**2)

a *= 2
print ("Doubled each element of original array:", a)
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]

In [11]:
import numpy as np
arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])

print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
print ("Column-wise minimum elements:",arr.min(axis = 0))
print ("Sum of all array elements:",arr.sum())
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]

In [12]:
import numpy as np
a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])
print ("Array sum:\n", a + b)
print ("Array multiplication:\n", a*b)
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]

In [13]:
import numpy as np
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]

In [14]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [15]:
import numpy as np

In [30]:
data=np.loadtxt("fitness.txt", dtype="str")

/tmp/ipython-input-3758556875.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data=np.loadtxt("fitness.txt", dtype="str")

In [31]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '100', '6', '8', '0', '65'],
       ['23-10-2017', '3158', '200', '99', '5', '0', '65'],
       ['24-10-2017', '4383', '200', '143', '4', '0', '64'],
       ['25-10-2017', '3881', '200', '125', '5', '0', '64'],
       ['26-10-2017', '4037', '200', '129', '6', '0', '64'],
       ['27-10-2017', '202', '200', '6', '8', '0', '64'],
       ['28-10-2017', '292', '200', '9', '5', '0', '64'],
       ['29-10-2017', '330', '300', '10', '6', '0', '64'],
       ['30-10-2017', '2209', '200', '72', '5', '0', '64'],
       ['31-10-2017', '4550', '300', '150', '8', '500', '64'],
       ['01-11-2017', '4435', '300', '141', '5', '0', '64'],
       ['02-11-2017', '4779', '300', '156', '4', '0', '64'],
       ['03-11-2017', '1831', '300', '57', '5', '0', '64'],
       ['04-11-2017', '2255', '300', '72', '4', '0', '64'],
       ['05-11-2017', '539', '300', '17', '5', '500', '64'],
       ['06-11-2017', '5464', '300', '181', '4', '0', '64'],
       ['07-11-2017', '6041', '200', '197', '3', '0', '64'],
       ['08-11-2017', '4068', '300', '131', '2', '0', '64'],
       ['09-11-2017', '4683', '300', '154', '9', '0', '64'],
       ['10-11-2017', '4033', '300', '137', '5', '0', '64'],
       ['11-11-2017', '6314', '300', '193', '6', '500', '64'],
       ['12-11-2017', '614', '300', '19', '4', '500', '64'],
       ['13-11-2017', '3149', '300', '101', '5', '500', '64'],
       ['14-11-2017', '4005', '300', '139', '8', '500', '64'],
       ['15-11-2017', '4880', '300', '164', '4', '500', '64'],
       ['16-11-2017', '4136', '300', '137', '5', '500', '64'],
       ['17-11-2017', '705', '300', '22', '6', '500', '64'],
       ['18-11-2017', '570', '200', '17', '5', '500', '64'],
       ['19-11-2017', '269', '300', '9', '6', '500', '64'],
       ['20-11-2017', '4275', '300', '145', '5', '0', '64'],
       ['21-11-2017', '5999', '300', '192', '6', '0', '64'],
       ['22-11-2017', '4421', '300', '146', '5', '0', '64'],
       ['23-11-2017', '6930', '300', '234', '6', '0', '64'],
       ['24-11-2017', '5195', '300', '167', '5', '0', '64'],
       ['25-11-2017', '546', '300', '16', '6', '0', '64'],
       ['26-11-2017', '493', '300', '17', '7', '500', '64'],
       ['27-11-2017', '995', '300', '32', '6', '500', '64'],
       ['28-11-2017', '1163', '200', '35', '7', '500', '64'],
       ['29-11-2017', '6676', '100', '220', '6', '500', '64'],
       ['30-11-2017', '3608', '300', '116', '5', '500', '64'],
       ['01-12-2017', '774', '300', '23', '6', '500', '64'],
       ['02-12-2017', '1421', '300', '44', '7', '500', '64'],
       ['03-12-2017', '4064', '300', '131', '8', '500', '64'],
       ['04-12-2017', '2725', '300', '86', '8', '500', '64'],
       ['05-12-2017', '5934', '300', '194', '7', '500', '64'],
       ['06-12-2017', '1867', '300', '60', '8', '500', '64'],
       ['07-12-2017', '3721', '100', '121', '5', '500', '64'],
       ['08-12-2017', '2374', '200', '76', '4', '0', '64'],
       ['09-12-2017', '2909', '200', '93', '3', '500', '64'],
       ['10-12-2017', '1648', '100', '53', '3', '500', '64'],
       ['11-12-2017', '799', '100', '25', '4', '0', '64'],
       ['12-12-2017', '7102', '200', '227', '5', '500', '64'],
       ['13-12-2017', '3941', '200', '125', '5', '500', '64'],
       ['14-12-2017', '7422', '300', '243', '5', '500', '64'],
       ['15-12-2017', '437', '200', '14', '3', '500', '64'],
       ['16-12-2017', '1231', '200', '39', '4', '500', '64'],
       ['17-12-2017', '1696', '100', '55', '4', '0', '64'],
       ['18-12-2017', '4921', '200', '158', '5', '500', '64'],
       ['19-12-2017', '221', '100', '7', '5', '500', '64'],
       ['20-12-2017', '6500', '200', '213', '5', '500', '64'],
       ['21-12-2017', '3575', '200', '116', '5', '500', '64'],
       ['22-12-2017', '4061', '100', '129', '5', '0', '64'],
       ['23-12-2017', '651', '100', '21', '5', '0', '64'],
       ['24-12-2017', '753', '100', '28', '4', '0', '64'],
       ['25-12-2017', '518', '100', '16', '3', '0', '64'],
       ['26-12-2017', '5537', '300', '180', '4', '500', '64'],
       ['27-12-2017', '4108', '200', '138', '5', '500', '64'],
       ['28-12-2017', '5376', '300', '176', '5', '500', '64'],
       ['29-12-2017', '3066', '200', '99', '4', '500', '64'],
       ['30-12-2017', '177', '100', '5', '5', '0', '64'],
       ['31-12-2017', '36', '100', '1', '3', '0', '64'],
       ['01-01-2018', '299', '100', '10', '3', '0', '64'],
       ['02-01-2018', '1447', '200', '47', '3', '0', '64'],
       ['03-01-2018', '2599', '200', '84', '2', '0', '64'],
       ['04-01-2018', '702', '100', '23', '3', '0', '64'],
       ['05-01-2018', '133', '100', '4', '2', '0', '64'],
       ['06-01-2018', '153', '300', '0', '8', '0', '64'],
       ['07-01-2018', '500', '200', '0', '5', '500', '64'],
       ['08-01-2018', '2127', '200', '0', '5', '0', '64'],
       ['09-01-2018', '2203', '300', '0', '5', '500', '64']], dtype='<U10')

In [32]:
data.shape

(96, 7)

In [33]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [34]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
        '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
        '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
        '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
        '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
        '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
        '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
        '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
        '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
       ['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230',
        '61', '1258', '3148', '4687', '4732', '3519', '1580', '2822',
        '181', '3158', '4383', '3881', '4037', '202', '292', '330',
        '2209', '4550', '4435', '4779', '1831', '2255', '539', '5464',
        '6041', '4068', '4683', '4033', '6314', '614', '3149', '4005',
        '4880', '4136', '705', '570', '269', '4275', '5999', '4421',
        '6930', '5195', '546', '493', '995', '1163', '6676', '3608',
        '774', '1421', '4064', '2725', '5934', '1867', '3721', '2374',
        '2909', '1648', '799', '7102', '3941', '7422', '437', '1231',
        '1696', '4921', '221', '6500', '3575', '4061', '651', '753',
        '518', '5537', '4108', '5376', '3066', '177', '36', '299',
        '1447', '2599', '702', '133', '153', '500', '2127', '2203'],
       ['200', '100', '100', '100', '200', '100', '100', '100', '100',
        '100', '100', '100', '300', '100', '100', '100', '100', '200',
        '200', '200', '200', '200', '200', '300', '200', '300', '300',
        '300', '300', '300', '300', '300', '200', '300', '300', '300',
        '300', '300', '300', '300', '300', '300', '300', '200', '300',
        '300', '300', '300', '300', '300', '300', '300', '300', '200',
        '100', '300', '300', '300', '300', '300', '300', '300', '100',
        '200', '200', '100', '100', '200', '200', '300', '200', '200',
        '100', '200', '100', '200', '200', '100', '100', '100', '100',
        '300', '200', '300', '200', '100', '100', '100', '200', '200',
        '100', '100', '300', '200', '200', '300'],
       ['181', '197', '0', '174', '223', '149', '140', '38', '1', '40',
        '101', '152', '150', '113', '49', '86', '6', '99', '143', '125',
        '129', '6', '9', '10', '72', '150', '141', '156', '57', '72',
        '17', '181', '197', '131', '154', '137', '193', '19', '101',
        '139', '164', '137', '22', '17', '9', '145', '192', '146', '234',
        '167', '16', '17', '32', '35', '220', '116', '23', '44', '131',
        '86', '194', '60', '121', '76', '93', '53', '25', '227', '125',
        '243', '14', '39', '55', '158', '7', '213', '116', '129', '21',
        '28', '16', '180', '138', '176', '99', '5', '1', '10', '47',
        '84', '23', '4', '0', '0', '0', '0'],
       ['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
        '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
        '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
        '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
        '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
        '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
        '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
        '2', '8', '5', '5', '5'],
       ['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
        '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
        '0', '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0',
        '500', '500', '500', '500', '500', '500', '500', '500', '500',
        '0', '0', '0', '0', '0', '0', '500', '500', '500', '500', '500',
        '500', '500', '500', '500', '500', '500', '500', '0', '500',
        '500', '0', '500', '500', '500', '500', '500', '0', '500', '500',
        '500', '500', '0', '0', '0', '0', '500', '500', '500', '500',
        '0', '0', '0', '0', '0', '0', '0', '0', '500', '0', '500'],
       ['66', '66', '66', '66', '66', '66', '66', '66', '66', '65', '65',
        '65', '65', '65', '65', '65', '65', '65', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
        '64', '64', '64', '64', '64', '64', '64', '64']], dtype='<U10')